<a href="https://colab.research.google.com/github/Jenoprabakar/TensorFlow-lab_experiments/blob/main/basic_mathematical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
print("a+b=",tf.add(a,b).numpy())
print("a-b=",tf.subtract(a,b).numpy())
print("a*b=",tf.multiply(a,b).numpy())
print("a/b=",tf.divide(a,b).numpy())
print("a**2=",tf.pow(a,2).numpy())




a+b= [5 7 9]
a-b= [-3 -3 -3]
a*b= [ 4 10 18]
a/b= [0.25 0.4  0.5 ]
a**2= [1 4 9]


In [5]:
A = tf.constant([1, 2, 3, 4], dtype=tf.float32)
A_reshaped = tf.reshape(A, (2, 2))
C = tf.constant([[5.0, 6.0], [7.0, 8.0]])
matmul1 = tf.matmul(A_reshaped, C)
matmul2 = tf.linalg.matmul(A_reshaped, C)
print("tf.matmul:\n", matmul1)
print("tf.linalg.matmul:\n", matmul2)
print("Shape of result:", matmul1.shape)


tf.matmul:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.linalg.matmul:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Shape of result: (2, 2)


In [8]:
import tensorflow as tf
T = tf.constant([[-1.0, -0.5, 0.0], [0.5, 1.0, 2.0]], )
print("Original Tensor :", T)
abs_T = tf.abs(T)
print("\nAbsolute Value:", abs_T)
safe_T_for_sqrt = tf.where(T < 0, tf.zeros_like(T), T)
sqrt_T = tf.sqrt(safe_T_for_sqrt)
print("\nSquare Root:\n", sqrt_T)
T_positive_only = tf.constant([[0.5, 1.0, 2.0]])
log_T = tf.math.log(T_positive_only)
print("\nNatural Log:\n", log_T)
exp_T = tf.exp(T)
print("\nExponential:\n", exp_T)
sin_T = tf.sin(T)
cos_T = tf.cos(T)
print("\nSine :\n", sin_T)
print("\nCosine :\n", cos_T)


Original Tensor : tf.Tensor(
[[-1.  -0.5  0. ]
 [ 0.5  1.   2. ]], shape=(2, 3), dtype=float32)

Absolute Value: tf.Tensor(
[[1.  0.5 0. ]
 [0.5 1.  2. ]], shape=(2, 3), dtype=float32)

Square Root:
 tf.Tensor(
[[0.         0.         0.        ]
 [0.70710677 1.         1.4142135 ]], shape=(2, 3), dtype=float32)

Natural Log:
 tf.Tensor([[-0.6931472  0.         0.6931472]], shape=(1, 3), dtype=float32)

Exponential:
 tf.Tensor(
[[0.36787945 0.60653067 1.        ]
 [1.6487212  2.7182817  7.389056  ]], shape=(2, 3), dtype=float32)

Sine :
 tf.Tensor(
[[-0.84147096 -0.47942555  0.        ]
 [ 0.47942555  0.84147096  0.9092974 ]], shape=(2, 3), dtype=float32)

Cosine :
 tf.Tensor(
[[ 0.5403023   0.87758255  1.        ]
 [ 0.87758255  0.5403023  -0.41614684]], shape=(2, 3), dtype=float32)


In [9]:
import tensorflow as tf
student_scores = tf.constant([[85, 90, 75],[92, 88, 80], [78, 95, 85]], dtype=tf.float32)
subject_weights = tf.constant([0.4, 0.3, 0.3], dtype=tf.float32)
weighted_scores = student_scores * subject_weights
final_scores = tf.reduce_sum(weighted_scores, axis=1)
print("Final Academic Scores for each student:\n", final_scores)


Final Academic Scores for each student:
 tf.Tensor([83.5      87.2      85.200005], shape=(3,), dtype=float32)
