<a href="https://colab.research.google.com/github/Jenoprabakar/TensorFlow-lab_experiments/blob/main/tensor_creation_and_basic_properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
scalar = tf.constant(2)
vector = tf.constant([10, 20, 30, 40, 50])
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])
tensor_3d = tf.constant([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
zeros_tensor = tf.zeros([3, 3])
ones_tensor = tf.ones([2, 4])
constant_tensor = tf.constant(7, shape=[2, 2, 2])
random_normal_tensor = tf.random.normal(shape=[3, 3], mean=0.0, stddev=1.0)
random_uniform_tensor = tf.random.uniform(shape=[2, 3], minval=0, maxval=10)

def print_tensor_info(name, tensor):
    print(f"\n{name}:")
    print(f"Value:\n{tensor.numpy()}")
    print(f"Shape: {tensor.shape}")
    print(f"Dtype: {tensor.dtype}")
    print(f"Rank: {tf.rank(tensor).numpy()}")

print_tensor_info("Scalar (0-D)", scalar)
print_tensor_info("Vector (1-D)", vector)
print_tensor_info("Matrix (2-D)", matrix)
print_tensor_info("3-D Tensor", tensor_3d)
print_tensor_info("Zeros Tensor (3x3)", zeros_tensor)
print_tensor_info("Ones Tensor (2x4)", ones_tensor)
print_tensor_info("Constant Tensor (2x2x2)", constant_tensor)
print_tensor_info("Random Normal Tensor (3x3)", random_normal_tensor)
print_tensor_info("Random Uniform Tensor (2x3)", random_uniform_tensor)



Scalar (0-D):
Value:
2
Shape: ()
Dtype: <dtype: 'int32'>
Rank: 0

Vector (1-D):
Value:
[10 20 30 40 50]
Shape: (5,)
Dtype: <dtype: 'int32'>
Rank: 1

Matrix (2-D):
Value:
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)
Dtype: <dtype: 'int32'>
Rank: 2

3-D Tensor:
Value:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dtype: <dtype: 'int32'>
Rank: 3

Zeros Tensor (3x3):
Value:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)
Dtype: <dtype: 'float32'>
Rank: 2

Ones Tensor (2x4):
Value:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (2, 4)
Dtype: <dtype: 'float32'>
Rank: 2

Constant Tensor (2x2x2):
Value:
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
Shape: (2, 2, 2)
Dtype: <dtype: 'int32'>
Rank: 3

Random Normal Tensor (3x3):
Value:
[[-1.2758533   1.8750099   0.5708747 ]
 [ 0.0057637   0.6017255   0.7954214 ]
 [ 0.8391036  -0.36677358  1.0699039 ]]
Shape: (3, 3)
Dtype: <dtype: 'float32'>
Rank: 2

Random Uniform Tensor (2x3):
Value:
[[0.7497275  4.742275   4.991975  ]
 [0.98486066 5.5208073  

In [ ]:
import tensorflow as tf
vector = tf.constant([10, 20, 30, 40, 50, 60])
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])
tensor_3d = tf.constant([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
def show_tensor(name, tensor):
    print(f"\n{name}")
    print("Value:\n", tensor.numpy())
    print("Shape:", tensor.shape)
    print("Rank:", tf.rank(tensor).numpy())

reshaped_vector = tf.reshape(vector, [2, -1])
show_tensor("Reshaped Vector (1D → 2x3)", reshaped_vector)

reshaped_matrix = tf.reshape(matrix, [2, -1])
show_tensor("Reshaped Matrix (2D → 2x3)", reshaped_matrix)

reshaped_tensor_3d = tf.reshape(tensor_3d, [2, -1])
show_tensor("Reshaped 3D Tensor (→ 2x6)", reshaped_tensor_3d)



Reshaped Vector (1D → 2x3)
Value:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Rank: 2

Reshaped Matrix (2D → 2x3)
Value:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Rank: 2

Reshaped 3D Tensor (→ 2x6)
Value:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape: (2, 6)
Rank: 2


In [ ]:
import tensorflow as tf
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
first_row = tensor[0]
second_row = tensor[1]
bottom_right = tensor[2, 2]
submatrix_2x2 = tensor[:2, :2]
print("Original Tensor:\n", tensor.numpy())
print("\nFirst Row:", first_row.numpy())
print("Second Row:", second_row.numpy())
print("Bottom-right Element:", bottom_right.numpy())
print("2x2 Submatrix:\n", submatrix_2x2.numpy())


Original Tensor:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

First Row: [1 2 3]
Second Row: [4 5 6]
Bottom-right Element: 9
2x2 Submatrix:
 [[1 2]
 [4 5]]


In [ ]:
import tensorflow as tf
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
float_tensor = tf.cast(int_tensor, dtype=tf.float32)
print("\nConverted Tensor (float32):", float_tensor.numpy())
print("Dtype:", float_tensor.dtype)



Converted Tensor (float32): [1. 2. 3.]
Dtype: <dtype: 'float32'>


In [ ]:
import tensorflow as tf

tensor = tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32)
print("Original Integer Tensor:\n", tensor.numpy())
print("Shape:", tensor.shape, "Dtype:", tensor.dtype)

reshaped = tf.reshape(tensor, [3, 2])
print("\nReshaped Tensor:\n", reshaped.numpy())
print("Shape:", reshaped.shape)

converted = tf.cast(reshaped, dtype=tf.float32)
print("\nConverted to float32:\n", converted.numpy())
print("Dtype:", converted.dtype)

added = converted + 0.5
print("\nAfter Adding 0.5:\n", added.numpy())


Original Integer Tensor:
 [[7 4 2]
 [5 7 6]]
Shape: (2, 3) Dtype: <dtype: 'int32'>

Reshaped Tensor:
 [[7 4]
 [2 5]
 [7 6]]
Shape: (3, 2)

Converted to float32:
 [[7. 4.]
 [2. 5.]
 [7. 6.]]
Dtype: <dtype: 'float32'>

After Adding 0.5:
 [[7.5 4.5]
 [2.5 5.5]
 [7.5 6.5]]
